name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node_version: "20.9.0"

      - run: npm ci

      - run: npm run test

      - run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy Pages
        uses: actions/deploy-pages@v2
